### ISSUE TITLE
League Overlay fails with error when autostarted

### ISSUE THREAD

**Issue by vith** [POE-Addon-Launcher/PAL2#17]
```
---------------------------
Overlay.ahk
---------------------------
Error at line 21.

#Include file "Gdip_All.ahk" cannot be opened.

The program will exit.
---------------------------
OK   
---------------------------
```

It works when launching manually by doubleclicking the addon in the installed list.

This was noticed in the issue for adding support for League Overlay [here](https://github.com/POE-Addon-Launcher/PAL2/issues/7#issuecomment-466625745) but deserves its own (open) issue.

**Comment by POE-Addon-Launcher** [comment]
Can't reproduce

**Comment by finlaybrown** [comment]
This can be fixed by opening "Overlay.ahk" and modifying the line
`#Include, Gdip_All.ahk`
And adding the full path like
`#Include, C:\Users\Username\AppData\Local\PAL\Addons\League Overlay\Gdip_All.ahk`

And doing the same for the 4 image files
`global image1 := "Syndicate.png"`
`global image2 := "Incursion.png"`
`global image3 := "Map.png"`
`global image4 := "Fossil.png"`
To
`global image1 := "C:\Users\Username\AppData\Local\PAL\Addons\League Overlay\Syndicate.png"`
`global image2 := "C:\Users\Username\AppData\Local\PAL\Addons\League Overlay\Incursion.png"`
`global image3 := "C:\Users\Username\AppData\Local\PAL\Addons\League Overlay\Map.png"`
`global image4 := "C:\Users\Username\AppData\Local\PAL\Addons\League Overlay\Fossil.png"`
